name: AvaReilly
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/edbcccdb-7a66-4c13-95ee-c1030dbb4b86.gif
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14adfcc7-7d96-4587-a6bf-73de3cb04c5d.gif
layout_spectrum: 0.22903805202804506
typography_spectrum: 0.6752310991287231
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.2196562490426004
  lightness: 0.480103479931131
  saturation: 0.3092156674247235
  rhythmicContrast: 0.08204361284151673
purpose:
  - type: contact
    label: Contact me!
    url: 'mailto:keith@keithreilly.com'
  - type: external
    label: 'http://www.playthruinc.com'
    url: 'http://www.playthruinc.com'
title: My Wonderful Life!
description: Growing up in the World!!
author:
  name: Keith Reilly
  email: Keith@KeithReilly.com
content_rating:
  adult: false
navigation:
  - name: Time with my Dad
    id: 73ea2e09-782f-4647-977f-a2eac248c022
    type: content
  - name: Doing things Right!!!
    id: 4f721adb-642f-40a1-8371-a30972318df6
    type: content
  - name: Time with My Mom
    id: bb8716c2-abc7-4486-8cfd-4b941216b3e0
    type: content
  - name: 'Time Spent Being Silly '
    id: 4f721adb-642f-40a1-8371-a30972318df6
    type: content
  - name: About Me
    id: 0ef26f58-99ab-4a5e-b11a-727efbd064e1
    type: content
content: []
github: true
