name: AvaReilly
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/edbcccdb-7a66-4c13-95ee-c1030dbb4b86.gif
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14adfcc7-7d96-4587-a6bf-73de3cb04c5d.gif
layout_spectrum: 0.22903805202804506
typography_spectrum: 0.6752310991287231
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.2196562490426004
  lightness: 0.480103479931131
  saturation: 0.3092156674247235
  rhythmicContrast: 0.08204361284151673
purpose:
  - type: contact
    label: Contact me!
    url: 'mailto:keith@keithreilly.com'
  - type: external
    label: 'http://www.playthruinc.com'
    url: 'http://www.playthruinc.com'
title: My Wonderful Life!
description: Growing up in the World!!
author:
  name: Keith Reilly
  email: Keith@KeithReilly.com
content_rating:
  adult: false
navigation:
  - name: Time with my Dad
    id: 73ea2e09-782f-4647-977f-a2eac248c022
    type: content
  - name: Doing things Right!!!
    id: 4f721adb-642f-40a1-8371-a30972318df6
    type: content
  - name: Time with My Mom
    id: bb8716c2-abc7-4486-8cfd-4b941216b3e0
    type: content
  - name: 'Time Spent Being Silly '
    id: 4f721adb-642f-40a1-8371-a30972318df6
    type: content
  - name: About Me
    id: 0ef26f58-99ab-4a5e-b11a-727efbd064e1
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FCOTMWI3kqw4%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCOTMWI3kqw4&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FCOTMWI3kqw4%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=COTMWI3kqw4'
      keywords:
        - ava
      title: Ava - 12-28-2011
      publisher:
        name: YouTube
        domain: www.youtube.com
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
      author:
        - name: R. Peds
          url: 'https://www.youtube.com/user/renee07430'
          avatar: {}
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FCOTMWI3kqw4%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCOTMWI3kqw4&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FCOTMWI3kqw4%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=COTMWI3kqw4'
      keywords:
        - ava
      title: Ava - 12-28-2011
      publisher:
        name: YouTube
        domain: www.youtube.com
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
      author:
        - name: R. Peds
          url: 'https://www.youtube.com/user/renee07430'
          avatar: {}
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FCOTMWI3kqw4%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCOTMWI3kqw4&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FCOTMWI3kqw4%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=COTMWI3kqw4'
      keywords:
        - ava
      title: Ava - 12-28-2011
      publisher:
        name: YouTube
        domain: www.youtube.com
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
      author:
        - name: R. Peds
          url: 'https://www.youtube.com/user/renee07430'
          avatar: {}
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FCOTMWI3kqw4%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCOTMWI3kqw4&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FCOTMWI3kqw4%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=COTMWI3kqw4'
      keywords:
        - ava
      title: Ava - 12-28-2011
      publisher:
        name: YouTube
        domain: www.youtube.com
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
      author:
        - name: R. Peds
          url: 'https://www.youtube.com/user/renee07430'
          avatar: {}
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
